"""add llm assessment columns and users table

Revision ID: 1b50f720d5d9
Revises: 54d56b992327
Create Date: 2026-08-13 07:02:28.116674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b50f720d5d9'
down_revision: Union[str, None] = '54d56b992327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('tender_scores', sa.Column('llm_overall_score', sa.Float(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_capability_score', sa.Float(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_sector_score', sa.Float(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_experience_score', sa.Float(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_win_probability', sa.Float(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_confidence', sa.String(length=10), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_recommendation', sa.String(length=20), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_rationale', sa.Text(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_scope_summary', sa.Text(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_matched_capabilities', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_relevant_projects', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_key_requirements', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_gaps', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_risks', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_suggested_team', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_model', sa.String(length=60), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_error', sa.Text(), nullable=True))
    op.add_column('tender_scores', sa.Column('llm_scored_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_scores', 'llm_scored_at')
    op.drop_column('tender_scores', 'llm_error')
    op.drop_column('tender_scores', 'llm_model')
    op.drop_column('tender_scores', 'llm_suggested_team')
    op.drop_column('tender_scores', 'llm_risks')
    op.drop_column('tender_scores', 'llm_gaps')
    op.drop_column('tender_scores', 'llm_key_requirements')
    op.drop_column('tender_scores', 'llm_relevant_projects')
    op.drop_column('tender_scores', 'llm_matched_capabilities')
    op.drop_column('tender_scores', 'llm_scope_summary')
    op.drop_column('tender_scores', 'llm_rationale')
    op.drop_column('tender_scores', 'llm_recommendation')
    op.drop_column('tender_scores', 'llm_confidence')
    op.drop_column('tender_scores', 'llm_win_probability')
    op.drop_column('tender_scores', 'llm_experience_score')
    op.drop_column('tender_scores', 'llm_sector_score')
    op.drop_column('tender_scores', 'llm_capability_score')
    op.drop_column('tender_scores', 'llm_overall_score')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
