"""baseline schema

Revision ID: 54d56b992327
Revises: 
Create Date: 2026-08-12 22:55:22.990295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54d56b992327'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('abbreviation', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('sub_cluster', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', name='uq_association_name_category')
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notices_found', sa.Integer(), nullable=True),
    sa.Column('notices_new', sa.Integer(), nullable=True),
    sa.Column('notices_updated', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('grading', sa.String(length=100), nullable=True),
    sa.Column('practice_group', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('years_of_experience', sa.Float(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('university', sa.String(length=200), nullable=True),
    sa.Column('education_level2', sa.String(length=50), nullable=True),
    sa.Column('graduation_year2', sa.Integer(), nullable=True),
    sa.Column('major2', sa.String(length=200), nullable=True),
    sa.Column('university2', sa.String(length=200), nullable=True),
    sa.Column('certification', sa.Text(), nullable=True),
    sa.Column('top_technical_skills', sa.Text(), nullable=True),
    sa.Column('self_development_areas', sa.Text(), nullable=True),
    sa.Column('cv_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name', name='uq_employee_full_name')
    )
    op.create_table('past_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('client', sa.String(length=500), nullable=True),
    sa.Column('practice_group', sa.String(length=200), nullable=True),
    sa.Column('sector_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_highlight', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name', name='uq_past_project_name')
    )
    op.create_table('practice_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.String(length=50), nullable=False),
    sa.Column('notice_type', sa.String(length=100), nullable=True),
    sa.Column('noticedate', sa.Date(), nullable=True),
    sa.Column('notice_status', sa.String(length=50), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_country', sa.String(length=100), nullable=True),
    sa.Column('bid_reference_no', sa.String(length=100), nullable=True),
    sa.Column('bid_description', sa.Text(), nullable=True),
    sa.Column('procurement_group', sa.String(length=10), nullable=True),
    sa.Column('procurement_method_code', sa.String(length=20), nullable=True),
    sa.Column('procurement_method_name', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('contact_organization', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.Column('notice_text', sa.Text(), nullable=True),
    sa.Column('notice_text_clean', sa.Text(), nullable=True),
    sa.Column('parsed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notice_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_flag', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_notice_id'), 'tenders', ['notice_id'], unique=True)
    op.create_index(op.f('ix_tenders_notice_status'), 'tenders', ['notice_status'], unique=False)
    op.create_index(op.f('ix_tenders_notice_type'), 'tenders', ['notice_type'], unique=False)
    op.create_index(op.f('ix_tenders_noticedate'), 'tenders', ['noticedate'], unique=False)
    op.create_index('ix_tenders_parsed_fields', 'tenders', ['parsed_fields'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tenders_project_country'), 'tenders', ['project_country'], unique=False)
    op.create_index(op.f('ix_tenders_sector'), 'tenders', ['sector'], unique=False)
    op.create_index('ix_tenders_status_deadline', 'tenders', ['notice_status', 'submission_deadline'], unique=False)
    op.create_index(op.f('ix_tenders_submission_deadline'), 'tenders', ['submission_deadline'], unique=False)
    op.create_table('capability_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_group_id', sa.UUID(), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['practice_group_id'], ['practice_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector', 'name', name='uq_capability_domain_sector_name')
    )
    op.create_table('crawl_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_run_id', sa.UUID(), nullable=True),
    sa.Column('notice_id', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_sectors',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sector_tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['past_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'sector_tag')
    )
    op.create_table('tender_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_notes_tender_id'), 'tender_notes', ['tender_id'], unique=False)
    op.create_table('tender_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('deadline_proximity_score', sa.Float(), nullable=True),
    sa.Column('capability_match_score', sa.Float(), nullable=True),
    sa.Column('sector_relevance_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('network_score', sa.Float(), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('matched_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('matched_projects', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gaps', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('risks', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id')
    )
    op.create_index('ix_tender_scores_overall', 'tender_scores', ['overall_score'], unique=False)
    op.create_table('employee_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('capability_domain_id', sa.UUID(), nullable=True),
    sa.Column('competency_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['capability_domain_id'], ['capability_domains.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'capability_domain_id', name='uq_employee_skill')
    )
    op.create_index(op.f('ix_employee_skills_capability_domain_id'), 'employee_skills', ['capability_domain_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_capability_domain_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index('ix_tender_scores_overall', table_name='tender_scores')
    op.drop_table('tender_scores')
    op.drop_index(op.f('ix_tender_notes_tender_id'), table_name='tender_notes')
    op.drop_table('tender_notes')
    op.drop_table('project_sectors')
    op.drop_table('crawl_errors')
    op.drop_table('capability_domains')
    op.drop_index(op.f('ix_tenders_submission_deadline'), table_name='tenders')
    op.drop_index('ix_tenders_status_deadline', table_name='tenders')
    op.drop_index(op.f('ix_tenders_sector'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_project_country'), table_name='tenders')
    op.drop_index('ix_tenders_parsed_fields', table_name='tenders', postgresql_using='gin')
    op.drop_index(op.f('ix_tenders_noticedate'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_notice_type'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_notice_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_notice_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('saved_searches')
    op.drop_table('practice_groups')
    op.drop_table('past_projects')
    op.drop_table('employees')
    op.drop_table('crawl_runs')
    op.drop_table('associations')
    # ### end Alembic commands ###
